name: Build

on:
  push:
    branches: [ update ]
  pull_request:
    branches: [ update ]

  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Assemble plugin
        run: ./gradlew jar

      - name: deploy plugin
        uses: actions/upload-artifact@v3
        with:
          name: plugin-jar
          path: build/libs/*
          retention-days: 2