name: Lint

on:
  push:
    branches: [ update ]
  pull_request:
    branches: [ update ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Change wrapper permission
        run: chmod +x ./gradlew

      - name: Run unit test
        run: ./gradlew ktlintCheck
