name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Change wrapper permission
        run: chmod +x ./gradlew

      - name: Assemble plugin
        run: ./gradlew jar

      - name: deploy plugin
        uses: actions/upload-artifact@v3
        with:
          name: plugin-jar
          path: build/libs/*
          retention-days: 2
