name: Test

on:
  workflow_run:
    workflows: [ Lint ]
    branches: [ update ]
    types: [ completed ]

  workflow_dispatch:
    input: {}

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run unit test
        run: ./gradlew test
